name: Docker

on:
  push:
    tags: [v*.*.*]

jobs:
  deploy:
    name: Deploy GCP Cloud Run
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
      LOCATION: europe-west1
    steps:
      - name: Login
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker eu.gcr.io --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Deploy Docker image
        run: >
          gcloud run deploy ${{ secrets.GCP_APP_NAME }}
          --image $IMAGE_NAME
          --region $LOCATION
          --min-instances=0
          --max-instances=1
          --platform managed
          --cpu=1
          --memory=512Mi
          --port=80
          --revision-suffix=${{ github.ref_name }}
